#!/usr/bin/python
"""
Alex Lindeman
2016-08-14
Returns interfaces monitored by vnstat as database dumps, via HTTP requests.
"""

import os, subprocess, sys, threading
from SimpleHTTPServer import SimpleHTTPRequestHandler
from SocketServer import TCPServer

if not subprocess.check_output(["which", "vnstat"]):
	print "vnstat does not appear to be installed"
	os.abort()

listen = ("0.0.0.0", 7654)
dir = "/var/lib/vnstat"

interfaces = sorted([ iface for iface in os.listdir(dir) if not iface.startswith(".") ])

class VnstatHandler(SimpleHTTPRequestHandler):
	def do_GET(self):

		code = 200
		iface = self.path[1:]

		if self.path == "/":
			response = "available interfaces: %s" % ", ".join(interfaces)
		elif iface in interfaces:
			response = subprocess.check_output(["vnstat", "-i", iface, "--dumpdb"])
		else:
			code = 404
			response = "that interface does not exist"

		self.send_response(code)
		self.send_header("Content-Type", "text/plain; charset=utf-8")
		self.end_headers()
		self.wfile.write(response + "\n")

try:
	handler = VnstatHandler
	httpd = TCPServer(listen, handler)
	print "listening on %s:%s from %s" % (listen[0], listen[1], dir)
	print "available interfaces: %s" % ", ".join(interfaces)
	httpd.serve_forever()

except:
	print "cleaning up"
	httpd.socket.close()
