#!/usr/bin/python
"""
Alex Lindeman
2016-08-14
Displays images from vnstati via HTTP requests.
"""

import os, subprocess
from SimpleHTTPServer import SimpleHTTPRequestHandler
from SocketServer import TCPServer

try:
	subprocess.check_output(["which", "vnstati"])
except:
	print "vnstati does not appear to be installed"
	exit()

listen = ("0.0.0.0", 7654)
wd = "/var/lib/vnstat"

if not os.path.isdir(wd):
	print "non-standard vnstat database directories are not currently supported"
	exit()

interfaces = sorted([ iface for iface in os.listdir(wd) if not iface.startswith(".") ])

class VnstatiHandler(SimpleHTTPRequestHandler):
	def do_GET(self):

		code = 200
		iface = self.path[1:]
		valid = iface in interfaces

		if valid:
			response = subprocess.check_output(["vnstati", "-s", "-i", iface, "-o", "-"])
		elif self.path == "/":
			response = "available interfaces: %s\n" % ", ".join(interfaces)
		else:
			code = 404
			response = "that interface does not exist or is not monitored\n"

		self.send_response(code)
		self.send_header("Content-Type", "image/png" if valid else "text/plain; charset=utf-8")
		self.end_headers()
		self.wfile.write(response)

handler = VnstatiHandler
httpd = TCPServer(listen, handler)

try:
	print "listening on %s:%s from %s" % (listen[0], listen[1], wd)
	print "available interfaces: %s" % ", ".join(interfaces)
	httpd.serve_forever()

except:
	print "cleaning up"
	httpd.socket.close()
